spring:
  datasource:
    url: jdbc:mysql://localhost/simdb?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: CHANGEME
    password: CHANGEME
    driverClassName: com.mysql.cj.jdbc.Driver
    continueOnError: true
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 25200000 #7*60*60*1000
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
  servlet:
    session:
      timeout: 0

google:
  clientId: CHANGEME
  clientSecret: canbeleftblank


