spring:
  datasource:
    url: jdbc:mysql://localhost/simdb?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: thecure7
    driverClassName: com.mysql.cj.jdbc.Driver
    continueOnError: true
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 25200000 #7*60*60*1000
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
  servlet:
    session:
      timeout: 0

google:
  clientId: 613395107842-nmr1dthih3c5ibcfcsrrkq61ef838ks8.apps.googleusercontent.com
  clientSecret: blank


